[package]
name = "aoc_2023_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.1.2"
once_cell = "1.18.0"
regex = "1.10.2"
